permalink: /:categories/:year/:month/:day/:title 
safe: true
lsi: false
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

name: Haruo's Blog
description: Douglas Haruo Lopes Nomizo Personal Blog
url: http://douglasnomizo.github.io

title : Haruo's Blog
tagline: 
author :
  name : Douglas Nomizo
  email : douglasnomizo@outlook.com
  github : douglasnomizo
  twitter : douglasnomizo
  feedburner : http://feeds.feedburner.com/github/DrYI

production_url : http://douglasnomizo.github.io

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : facebook
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 347951241973685
      num_posts: 10
      width: 580
      colorscheme: light

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-41038629-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  sharing :
    provider : all
    twitter :
       size :
       via :
       count :
    facebook :
       appid : 347951241973685
       layout : button_count
       font :
       faces : false
       width : 90
    googleplus :
       size : medium
       width :
       annotation : bubble
    linkedin :
       counter : right   